estimator:
  - name: age-extractor
    params: {}
  - name: discretizer
    params:
      bins_per_column:
        LotFrontage: 5
        LotArea: 3
      strategy: quantile
  - name: categorical-encoder
    params:
      one_hot: true
      force_dense_array: true
      additional_pass_through_columns:
        - HouseAge
        - RemodAddAge
        - GarageAge
      additional_categories:
        LotFrontage: [0.0, 1.0, 2.0, 3.0, 4.0]
        LotArea: [0.0, 1.0, 2.0]
  - name: standard-scaler
    params: {}
  - name: linear-regressor
    params: {}

data:
  filepath: ./dataset.csv

metrics:
  - name: mean absolute error
    params: {}

search:
  jobs: -1
  grid:
    - name: ridge-regressor
      params:
        alpha: [0.001, 0.01, 0.1, 1, 10, 100, 1000]

export:
  output_dir: ./models

reports:
  dir: ./reports