estimator:
  - name: age-extractor
    params: {}
  - name: categorical-encoder
    params:
      one_hot: false
      force_dense_array: true
      additional_pass_through_columns:
        - HouseAge
        - RemodAddAge
        - GarageAge
  - name: random-forest-regressor
    params: {}

data:
  filepath: ./dataset.csv

metrics:
  - name: mean absolute error
    params: {}

search:
  jobs: -1
  grid:
    - name: random-forest-regressor
      params:
        max_features: ["auto", "sqrt", "log2", null, 20, 30, 40, 50, 60]
        max_depth: [null, 2, 4, 8, 18, 32, 64, 128, 256]
        n_estimators: [2, 4, 8, 16, 32, 64, 128, 256, 512]

export:
  output_dir: ./models

reports:
  dir: ./reports